### ISSUE TITLE
Expired transactions

### ISSUE THREAD

**Issue by dpisarewski** [neo4jrb/neo4j-core#145]
`Transaction` does not update expiration timestamp and does not unregister expired transaction.

```
>> tx = ::Neo4j::Transaction.new
#<Neo4j::Server::CypherTransaction:0x007fcb311a0280 @connection=#<Faraday::Connection:0x007fcb29d4a9f8 @parallel_manager=nil, @headers={"Content-Type"=>"application/json", "User-Agent"=>"neo4j gem/3.0.4 (https://github.com/neo4jrb/neo4j)"}, @params={}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fcb29d4a458 @handlers=[FaradayMiddleware::EncodeJson, FaradayMiddleware::ParseJson, Faraday::Adapter::NetHttpPersistent], @app=#<FaradayMiddleware::EncodeJson:0x007fcb2a717cb0 @app=#<FaradayMiddleware::ParseJson:0x007fcb2a717d78 @app=#<Faraday::Adapter::NetHttpPersistent:0x007fcb2a717dc8 @app=#<Proc:0x007fcb2a717f58@/Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:152 (lambda)>>, @options={:content_type=>"application/json"}, @content_types=["application/json"]>>>, @url_prefix=#<URI::HTTP:0x007fcb29d4a048 URL:http:/>, @proxy=nil>, @commit_url="http://localhost:7474/db/data/transaction/6/commit", @exec_url="http://localhost:7474/db/data/transaction/6", @resource_url="http://localhost:7474/db/data/transaction", @resource_data={"commit"=>"http://localhost:7474/db/data/transaction/6/commit", "results"=>[], "transaction"=>{"expires"=>"Tue, 09 Dec 2014 12:38:34 +0000"}, "errors"=>[]}, @pushed_nested=0>

>> Thread.current[:neo4j_curr_tx].resource_data
{"commit"=>"http://localhost:7474/db/data/transaction/6/commit", "results"=>[], "transaction"=>{"expires"=>"Tue, 09 Dec 2014 12:38:34 +0000"}, "errors"=>[]}

>> User
User(access_token: Object, created_at: DateTime, email: Object, id: Object, password_digest: Object, updated_at: DateTime, username: Object)

>> sleep 60
60

>> User.first
 CYPHER 9ms MATCH (n:`User`) RETURN n ORDER BY n.uuid LIMIT 1
Neo4j::Session::CypherError: Unrecognized transaction id. Transaction may have timed out and been rolled back.
    from /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/neo4j-core-3.0.8/lib/neo4j-server/cypher_response.rb:168:in `raise_cypher_error'
    from /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/neo4j-core-3.0.8/lib/neo4j-core/query.rb:163:in `response'
    from /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/neo4j-core-3.0.8/lib/neo4j-core/query.rb:204:in `pluck'
    from /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/bundler/gems/neo4j-0e776e8ece07/lib/neo4j/active_node/query_methods.rb:15:in `first'
    from (irb):9
>> Thread.current[:neo4j_curr_tx].resource_data
{"commit"=>"http://localhost:7474/db/data/transaction/6/commit", "results"=>[], "transaction"=>{"expires"=>"Tue, 09 Dec 2014 12:38:34 +0000"}, "errors"=>[]}
```

**Comment by dpisarewski** [comment]
Here is it. https://github.com/neo4jrb/neo4j-core/pull/156
