### ISSUE TITLE
Non-rails project throws NameError "uninitialized constant Class::JSON"

### ISSUE THREAD

**Issue by benjineering** [neo4jrb/neo4j-core#262]
A simple non-rails project throws a `NameError` from `include 'neo4j':
```
/Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j/shared/type_converters.rb:243:in `convert_type': uninitialized constant Class::JSON (NameError)
	from /Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j/shared/type_converters.rb:343:in `register_converter'
	from /Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j/shared/type_converters.rb:312:in `block in included'
	from /Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j/shared/type_converters.rb:310:in `each'
	from /Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j/shared/type_converters.rb:310:in `included'
	from /Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j/type_converters.rb:5:in `include'
	from /Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j/type_converters.rb:5:in `<module:TypeConverters>'
	from /Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j/type_converters.rb:2:in `<module:Neo4j>'
	from /Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j/type_converters.rb:1:in `<top (required)>'
	from /Users/ben/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/ben/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/ben/.rvm/gems/ruby-2.2.2/gems/neo4j-6.1.12/lib/neo4j.rb:28:in `<top (required)>'
	from /Users/ben/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Users/ben/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Users/ben/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from test.rb:1:in `<main>'
```

### Code example

```
require 'neo4j'

class Item
  include Neo4j::ActiveNode
  property :name
end
```

### Runtime information:

Neo4j database version: `3.0.3`
`neo4j` gem version: `6.1.12`
`neo4j-core` gem version: `6.1.4`

**Comment by cheerfulstoic** [comment]
I think we fixed something like this in the past.  have you tried the latest version of the `neo4j` gem (7.1.1)?  There were also fixes in 7.0 which contain support for Neo4j 3.0.

**Comment by benjineering** [comment]
Ah yes, got myself confused about neo4j and neo4j-core version numbers - `neo4j 7.1.1` does the trick. Thanks!

**Comment by cheerfulstoic** [comment]
Awesome!
